=== vsslicer/vsslicer/vsslicer/modules/apps/profiles/schemas/material.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "./material.json",
  "title": "material",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "./defs.json#/$defs/id"
    },
    "inherits": {
      "type": "array",
      "items": {
        "$ref": "./defs.json#/$defs/id"
      }
    },
    "abstract": {
      "type": "boolean"
    },
    "when": {
      "$ref": "./defs.json#/$defs/condition"
    },
    "overrides": {
      "type": "array",
      "items": {
        "$ref": "./defs.json#/$defs/override"
      }
    },
    "settings": {
      "$ref": "./defs.json#/$defs/settings"
    },
    "renamed_from": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "meta": {
      "$ref": "./defs.json#/$defs/meta"
    },
    "vendor": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "diameter": {
      "type": "number",
      "exclusiveMinimum": 0
    },
    "brand": {
      "type": "string"
    },
    "color": {
      "type": "string"
    },
    "density": {
      "type": "number"
    },
    "cost": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number"
        },
        "currency": {
          "type": "string"
        },
        "per": {
          "enum": [
            "kg"
          ]
        }
      },
      "required": [
        "amount",
        "currency",
        "per"
      ],
      "additionalProperties": false
    },
    "spool_weight": {
      "type": "number"
    },
    "external_ids": {
      "type": "object",
      "properties": {
        "cura_guid": {
          "type": "string"
        },
        "bambu_filament_id": {
          "type": "string"
        },
        "orca_filament_id": {
          "type": "string"
        },
        "prusa_name": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "id",
    "vendor",
    "name",
    "type",
    "diameter"
  ],
  "additionalProperties": false
}

=== vsslicer/vsslicer/vsslicer/modules/common/profile-api/test/fixtures/nozzle/material-bambu-pla-basic.json
{
  "id": "bbl.pla-basic",
  "vendor": "bambu",
  "name": "Bambu PLA Basic",
  "type": "PLA",
  "diameter": 1.75,
  "brand": "Bambu Lab",
  "density": 1.26,
  "cost": {
    "amount": 15.99,
    "currency": "USD",
    "per": "kg"
  },
  "external_ids": {
    "cura_guid": "506c9f0d-e3aa-4bd4-b2d2-23e2425b1aa9",
    "bambu_filament_id": "OFoiVqVM",
    "orca_filament_id": "OFDSrzZ8",
    "prusa_name": "Prusament PLA @MK4S"
  },
  "settings": {
    "nozzle_temp": 220,
    "flow_ratio": 0.98,
    "cool_plate_temp": 35,
    "hot_plate_temp": 55,
    "textured_plate_temp": 55
  }
}
